<a href="https://colab.research.google.com/github/Cesarppz/Linux/blob/master/ia/ml/Comienzo_con_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
torch.__version__

'1.8.0+cu101'

# Operaciones de Tensores

---



In [ ]:
#Crear tensores
tensor = torch.tensor([[2,4,5],[8,4,7]])
print(tensor)
# Cambiar un dato
tensor[1][0] = 9
tensor

tensor([[2, 4, 5],
        [8, 4, 7]])


tensor([[2, 4, 5],
        [9, 4, 7]])

In [ ]:
#Tensor lleno de unos
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
#Tensor lleno aleatoriamenre
tensor_b = torch.Tensor(2,2)
print(tensor_b)
#Para hacer que esos valores aleatorios, se transladen a una escala de 0 a 1 , uso la fución uniform_()
tensor_b.uniform_()

tensor([[-2.6139e+03,  3.0681e-41],
        [ 0.0000e+00,  0.0000e+00]])


tensor([[0.2356, 0.2133],
        [0.7444, 0.3932]])

In [ ]:
#Otra manera de crear tensores aleatorios entre 0 y 1
tensor_c = torch.rand(2,3)
tensor_c

tensor([[0.5366, 0.1484, 0.3978],
        [0.1276, 0.6236, 0.5507]])

In [ ]:
#Ver las dimensiones de los tensores
tensor_c.shape

torch.Size([2, 3])

In [ ]:
#Cambiar las dimensiones de los tensores
reshaped = tensor_c.view(1,6)
reshaped2 = tensor_c.view(6,1)
print(reshaped,'\n', reshaped2)

tensor([[0.5366, 0.1484, 0.3978, 0.1276, 0.6236, 0.5507]]) 
 tensor([[0.5366],
        [0.1484],
        [0.3978],
        [0.1276],
        [0.6236],
        [0.5507]])


In [ ]:
#Ver la manera en la que se guarda un tensor
tensor_c.storage()

 0.536626935005188
 0.14839375019073486
 0.397754967212677
 0.12760627269744873
 0.6236472129821777
 0.550748884677887
[torch.FloatStorage of size 6]

In [ ]:
#Ver la manera en como se localiza los datos en ram
tensor_c.stride()

(3, 1)

In [ ]:
#Traspuestas
tensor_c.t()

tensor([[0.5366, 0.1276],
        [0.1484, 0.6236],
        [0.3978, 0.5507]])

In [ ]:
#Agregar dimenciones
tensor_x = torch.tensor([1,2,3,4])
tensor_x2 = torch.unsqueeze(tensor_x,0)
tensor_x3 = torch.unsqueeze(tensor_x,1)

print(tensor_x,'\n\nSe le agrega una dimención horizontal\n',tensor_x2,'\n\nSe le agrega una dimención vertical\n',tensor_x3)

tensor([1, 2, 3, 4]) 

Se le agrega una dimención horizontal
 tensor([[1, 2, 3, 4]]) 

Se le agrega una dimención vertical
 tensor([[1],
        [2],
        [3],
        [4]])


In [ ]:
#Transforma un numpy array
array = np.random.randn(2,2)
torch.from_numpy(array)

tensor([[-0.0703, -1.5229],
        [-0.1763,  1.0277]], dtype=torch.float64)

In [ ]:
tensor_c.size() , tensor.size()

(torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
tensor_c+ tensor

tensor([[2.5366, 4.1484, 5.3978],
        [9.1276, 4.6236, 7.5507]])

# Represantación de datos con tensores

---


In [ ]:
print('Original\n',tensor_c,'\n')
print('Promedio por columnas\n',torch.mean(tensor_c,dim=0),'\n')
print('Promedio por filas\n',torch.mean(tensor_c,dim=1))

Original
 tensor([[0.5366, 0.1484, 0.3978],
        [0.1276, 0.6236, 0.5507]]) 

Promedio por columnas
 tensor([0.3321, 0.3860, 0.4743]) 

Promedio por filas
 tensor([0.3609, 0.4340])


In [ ]:
#Guardar tensores
torch.save(tensor_c,'tensor')
n_tensor = torch.load('tensor')
n_tensor

tensor([[0.5366, 0.1484, 0.3978],
        [0.1276, 0.6236, 0.5507]])

In [ ]:
link = 'https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
df = pd.read_csv(link)
df.head()

Unnamed: 0      ID  ... GKReflexes  Release Clause
0           0  158023  ...        8.0         €226.5M
1           1   20801  ...       11.0         €127.1M
2           2  190871  ...       11.0         €228.1M
3           3  193080  ...       94.0         €138.6M
4           4  192985  ...       13.0         €196.4M

[5 rows x 89 columns]

In [ ]:
df.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [ ]:
subset = df[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna()
player = torch.tensor(subset.values).float()
player.shape,player.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [ ]:
data = player[:,1:]
target = player[:,0]
data.shape,target.shape

(torch.Size([18159, 4]), torch.Size([18159]))

In [ ]:
#Sacar le promedio y std de los datos
media = torch.mean(data,dim=0)
std = torch.std(data,dim=0)
media , std

(tensor([25.1225,  1.1132,  2.9473,  2.3613]),
 tensor([4.6706, 0.3940, 0.6605, 0.7562]))

In [ ]:
#Normalizo los datos 
data_n = (data - media)/std
data_n

tensor([[ 1.2584,  9.8641,  1.5939,  2.1671],
        [ 1.6866,  9.8641,  1.5939,  3.4896],
        [ 0.1879,  9.8641,  3.1080,  3.4896],
        ...,
        [-1.9532, -0.2873,  0.0798, -0.4778],
        [-1.7391, -0.2873,  0.0798, -0.4778],
        [-1.9532, -0.2873,  0.0798, -0.4778]])

In [ ]:
#Filtrar los datos 
#ge = greater or equal
#gt = greater than 
#lt = lower than 
good = data[torch.ge(target,85)]
medium = data[torch.gt(target,70)&torch.lt(target,85)]
bad = data[torch.lt(target,85)]

In [ ]:
good_mean = torch.mean(good,dim=0)
medium_mean = torch.mean(medium,dim=0)
bad_mean = torch.mean(bad,dim=0)
good_mean,medium_mean,bad_mean

(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([25.1029,  1.0994,  2.9443,  2.3572]))

In [ ]:
columns = subset.columns[1:]
columns

Index(['Age', 'International Reputation', 'Weak Foot', 'Skill Moves'], dtype='object')

In [ ]:
list(zip(columns,good_mean,medium_mean,bad_mean))

[('Age', tensor(28.3455), tensor(27.2285), tensor(25.1029)),
 ('International Reputation', tensor(3.3818), tensor(1.3561), tensor(1.0994)),
 ('Weak Foot', tensor(3.4455), tensor(3.1114), tensor(2.9443)),
 ('Skill Moves', tensor(3.0364), tensor(2.7515), tensor(2.3572))]

In [ ]:
for idx , value in enumerate(zip(columns,good_mean,medium_mean,bad_mean)):
  print('{:30}{:6.2f}{:6.2f}{:6.2f}'.format(*value))

Age                            28.35 27.23 25.10
International Reputation        3.38  1.36  1.10
Weak Foot                       3.45  3.11  2.94
Skill Moves                     3.04  2.75  2.36
