<a href="https://colab.research.google.com/github/Cesarppz/Linux/blob/master/ia/ml/Comienzo_con_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
torch.__version__

'1.1.0'

# Operaciones de Tensores

---



In [4]:
#Crear tensores
tensor = torch.tensor([[2,4,5],[8,4,7]])
print(tensor)
# Cambiar un dato
tensor[1][0] = 9
tensor

tensor([[2, 4, 5],
        [8, 4, 7]])


tensor([[2, 4, 5],
        [9, 4, 7]])

In [5]:
#Tensor lleno de unos
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [6]:
#Tensor lleno aleatoriamenre
tensor_b = torch.Tensor(2,2)
print(tensor_b)
#Para hacer que esos valores aleatorios, se transladen a una escala de 0 a 1 , uso la fución uniform_()
tensor_b.uniform_()

tensor([[-1.1736e-21,  3.0756e-41],
        [ 0.0000e+00,  0.0000e+00]])


tensor([[0.8826, 0.4637],
        [0.3629, 0.0276]])

In [7]:
#Otra manera de crear tensores aleatorios entre 0 y 1
tensor_c = torch.rand(2,3)
tensor_c

tensor([[0.2051, 0.1419, 0.7461],
        [0.1352, 0.6191, 0.7941]])

In [8]:
#Ver las dimensiones de los tensores
tensor_c.shape

torch.Size([2, 3])

In [9]:
#Cambiar las dimensiones de los tensores
reshaped = tensor_c.view(1,6)
reshaped2 = tensor_c.view(6,1)
print(reshaped,'\n', reshaped2)

tensor([[0.2051, 0.1419, 0.7461, 0.1352, 0.6191, 0.7941]]) 
 tensor([[0.2051],
        [0.1419],
        [0.7461],
        [0.1352],
        [0.6191],
        [0.7941]])


In [10]:
#Ver la manera en la que se guarda un tensor
tensor_c.storage()

 0.2051435112953186
 0.14193063974380493
 0.7461404800415039
 0.13516712188720703
 0.6190896034240723
 0.7940866947174072
[torch.FloatStorage of size 6]

In [11]:
#Ver la manera en como se localiza los datos en ram
tensor_c.stride()

(3, 1)

In [12]:
#Traspuestas
tensor_c.t()

tensor([[0.2051, 0.1352],
        [0.1419, 0.6191],
        [0.7461, 0.7941]])

In [13]:
#Agregar dimenciones
tensor_x = torch.tensor([1,2,3,4])
tensor_x2 = torch.unsqueeze(tensor_x,0)
tensor_x3 = torch.unsqueeze(tensor_x,1)

print(tensor_x,'\n\nSe le agrega una dimención horizontal\n',tensor_x2,'\n\nSe le agrega una dimención vertical\n',tensor_x3)

tensor([1, 2, 3, 4]) 

Se le agrega una dimención horizontal
 tensor([[1, 2, 3, 4]]) 

Se le agrega una dimención vertical
 tensor([[1],
        [2],
        [3],
        [4]])


In [14]:
#Transforma un numpy array
array = np.random.randn(2,2)
torch.from_numpy(array)

tensor([[-0.0238, -1.0241],
        [ 0.3633,  1.7393]], dtype=torch.float64)

In [15]:
tensor_c.size() , tensor.size()

(torch.Size([2, 3]), torch.Size([2, 3]))

In [18]:
tensor+ tensor

tensor([[ 4,  8, 10],
        [18,  8, 14]])

# Represantación de datos con tensores

---


In [19]:
print('Original\n',tensor_c,'\n')
print('Promedio por columnas\n',torch.mean(tensor_c,dim=0),'\n')
print('Promedio por filas\n',torch.mean(tensor_c,dim=1))

Original
 tensor([[0.2051, 0.1419, 0.7461],
        [0.1352, 0.6191, 0.7941]]) 

Promedio por columnas
 tensor([0.1702, 0.3805, 0.7701]) 

Promedio por filas
 tensor([0.3644, 0.5161])


In [20]:
#Guardar tensores
torch.save(tensor_c,'tensor')
n_tensor = torch.load('tensor')
n_tensor

tensor([[0.2051, 0.1419, 0.7461],
        [0.1352, 0.6191, 0.7941]])

In [21]:
link = 'https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
df = pd.read_csv(link)
df.head()

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [22]:
df.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [23]:
subset = df[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna()
player = torch.tensor(subset.values).float()
player.shape,player.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [24]:
data = player[:,1:]
target = player[:,0]
data.shape,target.shape

(torch.Size([18159, 4]), torch.Size([18159]))

In [25]:
#Sacar le promedio y std de los datos
media = torch.mean(data,dim=0)
std = torch.std(data,dim=0)
media , std

(tensor([25.1225,  1.1132,  2.9473,  2.3613]),
 tensor([4.6706, 0.3940, 0.6605, 0.7562]))

In [26]:
#Normalizo los datos 
data_n = (data - media)/std
data_n

tensor([[ 1.2584,  9.8641,  1.5939,  2.1671],
        [ 1.6866,  9.8641,  1.5939,  3.4896],
        [ 0.1879,  9.8641,  3.1080,  3.4896],
        ...,
        [-1.9532, -0.2873,  0.0798, -0.4778],
        [-1.7391, -0.2873,  0.0798, -0.4778],
        [-1.9532, -0.2873,  0.0798, -0.4778]])

In [27]:
#Filtrar los datos 
#ge = greater or equal
#gt = greater than 
#lt = lower than 
good = data[torch.ge(target,85)]
medium = data[torch.gt(target,70)&torch.lt(target,85)]
bad = data[torch.lt(target,85)]

In [28]:
good_mean = torch.mean(good,dim=0)
medium_mean = torch.mean(medium,dim=0)
bad_mean = torch.mean(bad,dim=0)
good_mean,medium_mean,bad_mean

(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([25.1029,  1.0994,  2.9443,  2.3572]))

In [29]:
columns = subset.columns[1:]
columns

Index(['Age', 'International Reputation', 'Weak Foot', 'Skill Moves'], dtype='object')

In [30]:
list(zip(columns,good_mean,medium_mean,bad_mean))

[('Age', tensor(28.3455), tensor(27.2285), tensor(25.1029)),
 ('International Reputation', tensor(3.3818), tensor(1.3561), tensor(1.0994)),
 ('Weak Foot', tensor(3.4455), tensor(3.1114), tensor(2.9443)),
 ('Skill Moves', tensor(3.0364), tensor(2.7515), tensor(2.3572))]

In [31]:
for idx , value in enumerate(zip(columns,good_mean,medium_mean,bad_mean)):
  print('{:30}{:6.2f}{:6.2f}{:6.2f}'.format(*value))

Age                            28.35 27.23 25.10
International Reputation        3.38  1.36  1.10
Weak Foot                       3.45  3.11  2.94
Skill Moves                     3.04  2.75  2.36


In [45]:
new_tensor = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(new_tensor,
      torch.mean(new_tensor, dim=1),
      torch.mean(new_tensor, dim=0),
      torch.mean(new_tensor)) 


tensor([[1., 2.],
        [3., 4.]]) tensor([1.5000, 3.5000]) tensor([2., 3.]) tensor(2.5000)


In [40]:
new_tensor.shape

torch.Size([2, 2])

In [44]:
print(torch.unsqueeze(new_tensor, 0).shape)

torch.Size([1, 2, 2])


In [35]:
tensorX = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(tensorX, 1))
tensorX = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(tensorX, 1))

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])
